name: CI Actions

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
   job1:
     name: Install Dependencies
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
            node-version: '18'

         name: Install Dependencies
         run: npm install

    job2:
      name: Run Tests
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4

           with:
             node-version: '18'

          - name: Install Dependencies
            run: npm install

          - name: Run Tests
            run: npm tests

      job3:
         name: Build Project
         runs-on: ubuntu-latest

         steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4

            with:
              node-version: '18'

          - name: Install Dependencies
            run: npm install

          - name: Build Project
            run: npm run build
